# Generated by Django 5.1.1 on 2024-09-12 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apanel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='admin_name',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='admin_email',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='admin_password',
        ),
    ]
