# Generated by Django 5.1.1 on 2024-09-16 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0008_librarys'),
        ('spanel', '0006_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='library_profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='library.librarys'),
            preserve_default=False,
        ),
    ]
