# Generated by Django 5.1.1 on 2024-09-16 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spanel', '0007_student_library_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='library_profile',
        ),
    ]
